# Generated by Django 5.0.3 on 2024-04-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_category_options_rename_title_category_name_and_more'),
    ]

    operations = [

    ]
